### ISSUE TITLE
Cooperating with ConnectionEvents and publish limit publishing own events

### ISSUE THREAD

**Issue by damonmaria** [rickkas7/electronsample#2]
Feature request:
If I publish my own events, and `ConnectionEvents` happens to also be publishing at the same time, then we could easily hit the publish limit. This is likely if the modem is being powered off and both `ConnectionEvents` and my own code are buffering events while offline.

It would be easy to cooperate with `ConnectionEvents` if the [3 guard conditions at the top of `ConnectionEvents::loop`](https://github.com/rickkas7/electronsample/blob/master/src/ConnectionEvents.cpp#L43-L56) where exposed as a method, something along the lines of `ConnectionEvents::canPublish()`. And to complete the circle there'd also have to be `ConnectionEvents::published()` which set `connectionEventLastSent`.

**Comment by rickkas7** [comment]
Good idea. I exposed canPublish() and publishedCompleted() in version 0.2.3.

**Comment by damonmaria** [comment]
Just FYI I've been using this feature and it works great. Thanks!
